version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"   # Frontend
      - "5000:5000"   # Backend
    environment:

      - REACT_APP_BACKEND_URL=http://localhost:5000

      - SERVER_PORT=5000
      - NODE_ENV=production
    volumes:
      - /app/node_modules